alias: ESP32 - Rafraîchir InfoHA
description: Envoyer toutes les valeurs toutes les 30s
triggers:
  - trigger: time_pattern
    minutes: /3
actions:
  - action: mqtt.publish
    data:
      topic: stationair/data/slot1
      qos: 0
      retain: false
      payload: >-
        {{ states('sensor.routeur_rms_puissance_m_soutiree') | float(0) |
        round(0) }}
  - action: mqtt.publish
    data:
      topic: stationair/data/slot2
      qos: 0
      retain: false
      payload: "{{ states('sensor.elec_moun_s_puissance') | float(0) | round(0) }}"
  - action: mqtt.publish
    data:
      topic: stationair/data/slot3
      qos: 0
      retain: false
      payload: >-
        {{ state_attr('weather.forecast_maison', 'temperature') | float(0) |
        round(0) }}
  - action: mqtt.publish
    data:
      topic: stationair/data/slot4
      qos: 0
      retain: false
      payload: >-
        {{ states('sensor.rennes_ballon_evier_relais_ouverture') | float(0) |
        round(0) }}
